In [2]:
import numpy as np
import pandas as pd
from datetime import datetime
from datetime import timedelta
from datetime import date
import matplotlib.pyplot as plt

import sys
sys.path.insert(0, './load_data')
from load import load_stats, load_history, load_td
pd.options.mode.chained_assignment = None

# Load Data

In [3]:
players = load_stats()
history = load_history()
td = load_td()

juniors = players[(players['Age'] <= timedelta(19*365)) & (players['Tournaments Played'] >= 10)]

In [11]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10344 entries, 0 to 10343
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    10344 non-null  int64
 1   First Name              10343 non-null  object
 2   Last Name               10342 non-null  object
 3   Database#               10344 non-null  int64
 4   USATT#                  10344 non-null  int64
 5   Location                9031 non-null   object
 6   Home Club               3056 non-null   object
 7   Tournament Rating       10344 non-null  int64
 8   Last Played Tournament  10344 non-null  datetime64[ns]
 9   League Rating           10344 non-null  int64
 10  Last Played League      4089 non-null   datetime64[ns]
 11  Membership Expiration   10344 non-null  object
 12  State                   6739 non-null   object
 13  Zip                     9184 non-null   object
 14  Gender                  10048 non-null  object
 15  Date of Birth           10099 non-null  datetime64[ns]
 16  Expiration Date         10344 non-null  object
 17  Max Rating              10309 non-null  float64
 18  Age                     10099 non-null  timedelta64[ns]
 19  Tournaments Played      10336 non-null  float64
dtypes: datetime64[ns](3), float64(2), int64(5), object(9), timedelta64[ns](1)
memory usage: 1.6+ MB

In [ ]:
players[(players['Zip'].str.len() != 5) & (players['Zip'].str.len() != 10)]

,Rank,First Name,Last Name,Database#,USATT#,Location,Home Club,Tournament Rating,Last Played Tournament,League Rating,Last Played League,Membership Expiration,State,Zip,Gender,Date of Birth,Expiration Date,Max Rating,Age,Tournaments Played
0,1,Kalinikos,Kreanga,69780,14365,FN,NaN,2851,2023-10-29,0,NaT,ACTIVE,FN,0,M,1900-01-01,2024-11-01,2871.0,45586 days,3.0
4,5,Kayama,Yu,185698,1185698,NaN,NaN,2779,2024-08-04,0,NaT,ACTIVE,NaN,0,M,NaT,2025-08-08,2779.0,NaT,1.0
6,7,Taehyun,Kim,182757,1182757,NaN,NaN,2772,2024-09-08,0,NaT,ACTIVE,NaN,NaN,M,1900-01-01,2024-12-01,2798.0,45586 days,7.0
7,8,Taimu,Arinobu,121652,220652,NaN,NaN,2769,2024-08-04,0,NaT,ACTIVE,NaN,0,M,1994-10-12,2025-08-08,2799.0,10969 days,3.0
13,16,Hiromitsu,Kasahara,3639,96676,JP,NaN,2730,2024-09-02,0,NaT,ACTIVE,JP,0,M,1983-06-27,2024-12-16,2829.0,15094 days,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10333,10471,Armaan,Hussain,181409,280409,NaN,NaN,10,2023-09-24,1,2023-09-23,ACTIVE,NaN,NaN,M,2006-12-09,2024-09-22,10.0,6528 days,1.0
10336,10474,Sion,Woo,182548,281548,NaN,NaN,6,2024-09-02,108,2024-09-08,ACTIVE,NaN,NaN,M,2015-09-25,2024-11-10,61.0,3316 days,4.0
10338,10476,Navin,Saravanakumar,184493,283493,CA,NaN,4,2024-07-28,104,2024-09-07,ACTIVE,CA,NaN,NaN,2011-04-01,2026-04-29,4.0,4954 days,1.0
10341,10479,Nicole,Leung,182143,1182143,NaN,NaN,2,2024-06-15,0,2023-10-14,ACTIVE,NaN,0,F,2014-05-28,2025-10-20,2.0,3801 days,1.0
10343,10481,saarth,chawla,183356,282356,NaN,NaN,1,2024-02-04,133,2024-09-08,ACTIVE,NaN,NaN,M,2012-04-07,2025-01-28,1.0,4582 days,1.0

In [ ]:
players[(players['Date of Birth'] == '1900-01-01')]

,Rank,First Name,Last Name,Database#,USATT#,Location,Home Club,Tournament Rating,Last Played Tournament,League Rating,Last Played League,Membership Expiration,State,Zip,Gender,Date of Birth,Expiration Date,Max Rating,Age,Tournaments Played
0,1,Kalinikos,Kreanga,69780,14365,FN,NaN,2851,2023-10-29,0,NaT,ACTIVE,FN,0,M,1900-01-01,2024-11-01,2871.0,45586 days,3.0
6,7,Taehyun,Kim,182757,1182757,NaN,NaN,2772,2024-09-08,0,NaT,ACTIVE,NaN,NaN,M,1900-01-01,2024-12-01,2798.0,45586 days,7.0
53,57,Senura,Silva,176286,275286,"Akron, OH",NaN,2601,2024-09-02,2382,2024-09-08,ACTIVE,OH,0,NaN,1900-01-01,2024-08-19,2621.0,45586 days,27.0
145,149,Fukuhara,Akio,178071,1178071,Saitama,NaN,2494,2024-08-25,0,NaT,ACTIVE,NaN,0,M,1900-01-01,2025-05-07,2514.0,45586 days,7.0
509,515,Don,Kim,69660,14179,"Fremont, CA",ICC Table Tennis Center,2239,2018-03-02,1813,2024-08-03,ACTIVE,CA,94539,M,1900-01-01,2025-05-05,2279.0,45586 days,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9757,9875,Josh,Rabinowitz,89207,61661,"Brooklyn, NY",NaN,477,2024-03-03,0,NaT,ACTIVE,NY,0,M,1900-01-01,2024-12-05,517.0,45586 days,2.0
9905,10027,Dominik,Bruszewski,184427,1184427,Hoffman Estates,NaN,407,2024-04-21,0,NaT,ACTIVE,NaN,60169,M,1900-01-01,2025-04-23,407.0,45586 days,1.0
10026,10151,Sunil,Patil,182803,1182803,Pleasanton,NaN,324,2023-12-03,0,NaT,ACTIVE,NaN,0,M,1900-01-01,2024-12-05,324.0,45586 days,1.0
10057,10185,Kabeer,Mehta,175474,274474,"-, CA",NaN,301,2023-04-16,164,2024-07-27,ACTIVE,CA,-,NaN,1900-01-01,2025-02-22,301.0,45586 days,1.0
10207,10343,Sarkar,Shavi,180598,1180598,NaN,NaN,114,2024-08-10,0,NaT,ACTIVE,NaN,NaN,NaN,1900-01-01,2025-08-13,114.0,45586 days,2.0

In [ ]:
active_index = td['Expiration Date'] >= '2024-09-11'
active = td[active_index]
sus = active[~(active['Member ID'].isin(players['USATT#'])) & ~(active['Member ID'].isin(history['USATT#']))]
len(sus)

51

In [ ]:
def initrating(player):
    rhist = history[history['Database#'] == player['Database#']]
    return rhist.iloc[-1, 13]
sus = history[~history['USATT#'].isin(td['Member ID'])]
t = sus.apply(initrating, axis=1)
t

1344      0.0
1345      0.0
7561      0.0
12240     0.0
12241     0.0
         ...
195350    0.0
195368    0.0
195386    0.0
195667    0.0
195678    0.0
Length: 143, dtype: float64

In [ ]:
len(players)

10344

In [ ]:
len(history['Database#'].unique())

10489

In [ ]:
histnoplayers = history[~history['Database#'].isin(players['Database#'])]
playersnohist = players[~players['Database#'].isin(history['Database#'])]
histnotd = history[~history['USATT#'].isin(td['Member ID'])]
sus = histnoplayers[~histnoplayers['USATT#'].isin(histnotd['USATT#'])]['USATT#'].unique()

In [ ]:
print(len(histnoplayers['Database#'].unique()))
print(len(histnotd['Database#'].unique()))

145
137

In [ ]:
sus = players[~players['USATT#'].isin(active['Member ID'])]
td[td['Member ID'].isin(sus['USATT#'])]

,Member ID,Last Name,First Name,Rating,State,Zip,Gender,Date of Birth,Expiration Date,Last Played Date
130,22497,Alto,Earl,2431,CA,92126,M,1988-05-04,2024-07-31,2023-04-09
336,78800,Baldonado,Jones,2183,NV,89169,M,1963-12-06,2024-06-07,2023-06-04
361,88635,Banu,George,1671,OK,73099,M,1978-02-27,2023-01-20,2022-04-02
901,4752,Chan,Oswald,1938,CA,91202,M,1961-12-21,2016-06-02,2018-03-02
994,93379,Chen,Bob,2688,CA,95121,M,1994-01-05,2024-07-03,2019-12-21
...,...,...,...,...,...,...,...,...,...,...
71057,280113,Kirsur,Nikhil,145,NaN,NaN,M,2009-10-02,2024-08-27,2024-06-22
71110,1181218,Liu,Wei,962,NaN,20148,F,1959-04-30,2024-09-04,2024-05-05
71118,1181229,Peng,Justin,963,PA,18940,M,2008-12-03,2024-09-05,2024-08-04
71119,1181230,Rao,Pranav,544,NaN,0,M,2009-06-13,2024-09-05,2023-12-03
72043,1183029,Shi,Grace,780,CA,92130,F,2012-03-18,2023-12-21,2023-12-21

In [ ]:
def rating_check(player):
    rhist = history[history['Database#'] == player['Database#']].reset_index()
    return rhist.loc[:len(rhist)-2, 'Initial Rating'].equals(rhist.loc[1:, 'Final Rating'].reset_index(drop=True))

rcheck = players.apply(rating_check, axis=1)

In [ ]:
len(players) - rcheck.sum()

876

In [ ]:
td.duplicated()[td.duplicated() == True]

Series([], dtype: bool)

In [ ]:
players

,Rank,First Name,Last Name,Database#,USATT#,Location,Home Club,Tournament Rating,Last Played Tournament,League Rating,Last Played League,Membership Expiration,State,Zip,Gender,Date of Birth,Expiration Date,Max Rating,Age,Tournaments Played
0,1,Kalinikos,Kreanga,69780,14365,FN,NaN,2851,2023-10-29,0,NaT,ACTIVE,FN,0,M,1900-01-01,2024-11-01,2871.0,45586 days,3.0
1,2,Lei,Kou,165420,1165420,"Milpitas, CA",Kou Lei Table Tennis Club,2810,2024-04-07,2816,2022-08-28,ACTIVE,CA,95035,M,1987-11-20,2025-06-29,2864.0,13487 days,40.0
2,3,Enzo,Angles,169130,1169130,"Vila Nova De Gaia, FN",NaN,2808,2024-09-08,0,NaT,ACTIVE,FN,11111,M,1995-02-05,2024-09-02,NaN,10853 days,NaN
3,4,Kanak,Jha,3431,72193,"Milpitas, CA",888 Table Tennis Center,2806,2024-07-07,2737,2017-04-08,ACTIVE,CA,95035,M,2000-06-19,2100-02-28,2806.0,8892 days,67.0
4,5,Kayama,Yu,185698,1185698,NaN,NaN,2779,2024-08-04,0,NaT,ACTIVE,NaN,0,M,NaT,2025-08-08,2779.0,NaT,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10339,10477,Easton,Deng,177517,276517,"San Jose, CA",NaN,3,2023-06-03,442,2024-09-01,ACTIVE,CA,95129,M,2016-04-04,2024-11-18,3.0,3124 days,2.0
10340,10478,Steve,Roberts,178929,277929,"Walnut Creek, CA",NaN,3,2024-06-22,8,2024-02-24,ACTIVE,CA,94597,M,1962-05-02,2025-03-10,37.0,22820 days,5.0
10341,10479,Nicole,Leung,182143,1182143,NaN,NaN,2,2024-06-15,0,2023-10-14,ACTIVE,NaN,0,F,2014-05-28,2025-10-20,2.0,3801 days,1.0
10342,10480,Rounak,Sengupta,184322,1184322,San Ramon,NaN,1,2024-05-12,0,2024-04-20,ACTIVE,NaN,94583,M,2010-08-10,2025-04-16,24.0,5188 days,2.0
10343,10481,saarth,chawla,183356,282356,NaN,NaN,1,2024-02-04,133,2024-09-08,ACTIVE,NaN,NaN,M,2012-04-07,2025-01-28,1.0,4582 days,1.0

In [ ]:
df = players['Date of Birth'].value_counts(dropna=False).sort_values(ascending=False)
print(df)

Date of Birth
NaT           245
1900-01-01    106
1997-07-07     16
1990-09-09     15
2000-01-01     10
             ...
1997-05-10      1
1967-02-24      1
1987-03-17      1
1981-05-21      1
2012-04-07      1
Name: count, Length: 8267, dtype: int64

In [ ]:
players['Date of Birth'].astype(str).str.slice(5,10).value_counts(dropna=False)

Date of Birth
         245
01-01    189
09-09     64
12-31     47
04-20     45
        ...
02-13     16
03-09     16
01-17     16
08-09     14
02-29      8
Name: count, Length: 367, dtype: int64